# Version of the specs, only for internal usage if this format should ever change drastically
_specver: 2

# modpack related settings, changes the supposed to change the visual appearance of the launcher
modpack:
  name: Ragnamod VI
  description: Ragnamod VI By MLDEG & Alkasym

# settings regarding the installation of the modpack
install:
  # version of minecraft, needs the exact version
  mcVersion: 1.16.5
  loaderVersion: ~
  installerUrl: "http://files.minecraftforge.net/maven/net/minecraftforge/forge/{{@mcversion@}}-{{@loaderversion@}}/forge-{{@mcversion@}}-{{@loaderversion@}}-installer.jar"
  installerArguments:
    - "--installServer"
  modpackUrl: https://media.forgecdn.net/files/4014/521/Ragnamod-VI-6.1.7.zip
  modpackFormat: curse

  # Settings which are specific to the format used, might not be needed in some casese
  formatSpecific:
    # optional paramenter used for curse to specify a whole project to ignore (mostly if it is client side only)
    ignoreProject:
      - 263420
      - 317780
      - 232131
      - 231275
      - 367706
      - 261725
      - 243863
      - 305373
      - 325492
      - 296468
      - 308240
      - 362791
      - 291788
      - 326950
      - 237701
      - 391382
      - 448233
      - 358191
      - 271740
      - 428199
      - 431430
      - 270441
      - 417179 # Caged Mobs
      - 428877 # BetterEnd (Forge)
      - 400012 # Ex Nihilo: Sequentia

  baseInstallPath: server/
  ignoreFiles:
    - mods/Overrides.txt
    - mods/optifine*.jar
    - mods/optiforge*.jar
    - resources/**
    - openloader/resources/**

  additionalFiles:
  localFiles:
    - from: server-icon.png
      to: server/server-icon.png
    - from: server.properties
      to: server/server.properties
    - from: mods/betterendforge-1.16.5-1.6.3.jar
      to: server/mods/betterendforge-1.16.5-1.6.3.jar
    - from: mods/cagedmobs-1.16.5-1.3.8.jar
      to: server/mods/cagedmobs-1.16.5-1.3.8.jar
  checkFolder: true
  installLoader: true
  spongeBootstrapper: https://github.com/simon816/SpongeBootstrap/releases/download/v0.7.1/SpongeBootstrap-0.7.1.jar
  connectTimeout: 30
  readTimeout: 30

  # In order to obtain the download urls for mods enclosed in a curseforge format, you must provide an
  # API key. Please visit https://github.com/Ocraftyone/ServerStarter-CFCorePatch for more details
  # on how to obtain a key. This can be omitted if you are using the zip modpackFormat.
  curseForgeAPIKey: XXX

launch:
  spongefix: false
  ramDisk: false
  checkOffline: true
  checkUrls:
    - https://github.com/
    - https://www.curseforge.com/
  maxRam: 12G
  minRam: 8G
  autoRestart: true
  crashLimit: 10
  crashTimer: 60min
  preJavaArgs: ~
  startFile: "forge-{{@mcversion@}}-{{@loaderversion@}}.jar"
  startCommand:
    - "-jar"
    - "{{@startFile@}}"
    - "nogui"
  forcedJavaPath: ~
  javaArgs:
    - "-Dfml.readTimeout=600"
    - "-Dfml.loginTimeout=600"
    - "-Dfml.queryResult=confirm"
    - "-XX:+UseG1GC"
    - "-XX:+ParallelRefProcEnabled"
    - "-XX:MaxGCPauseMillis=200"
    - "-XX:+UnlockExperimentalVMOptions"
    - "-XX:+DisableExplicitGC"
    - "-XX:+AlwaysPreTouch"
    - "-XX:G1NewSizePercent=30"
    - "-XX:G1MaxNewSizePercent=40"
    - "-XX:G1HeapRegionSize=8M"
    - "-XX:G1ReservePercent=20"
    - "-XX:G1HeapWastePercent=5"
    - "-XX:G1MixedGCCountTarget=4"
    - "-XX:InitiatingHeapOccupancyPercent=15"
    - "-XX:G1MixedGCLiveThresholdPercent=90"
    - "-XX:G1RSetUpdatingPauseTimePercent=5"
    - "-XX:SurvivorRatio=32"
    - "-XX:+PerfDisableSharedMem"
    - "-XX:MaxTenuringThreshold=1"
